[project]
name = "okcoin-python-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.3",
    "websockets>=14.1",
]

[dependency-groups]
dev = [
    "ruff>=0.8.2",
]
